osx_image: xcode8.3
language: objective-c

before_install:
  - gem install cocoapods -v '1.2.1'
  - pod --version
  - pod repo update --silent
  - brew outdated carthage || brew upgrade carthage

install:
  - pushd Example; pod install; popd;
  - if [[ ! $(which xcpretty) ]]; then gem install xcpretty --user-install; fi;

env:
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 7"
    - DESTINATION="platform=iOS Simulator,OS=9.0,name=iPhone 6"
    - DESTINATION="platform=iOS Simulator,OS=8.3,name=iPhone 4S"

before_script:
  - carthage bootstrap --platform iOS

script:
  - xcodebuild -workspace Example/ReCaptcha.xcworkspace -scheme ReCaptcha-Example -destination "$DESTINATION" build | xcpretty
  - xcodebuild -workspace Example/ReCaptcha.xcworkspace -scheme ReCaptcha-Example -destination "$DESTINATION" test | xcpretty

after_success:
  - pod lib lint --verbose
  - carthage build --no-skip-current --platform iOS
  - bash <(curl -s https://codecov.io/bash) -J 'ReCaptcha'
