osx_image: xcode9
language: objective-c

script:
  - bundle exec fastlane ci

deploy:
  - provider: script
    script: bundle exec fastlane release
    skip_cleanup: true
    on:
      repo: fjcaetano/ReCaptcha
      tags: true
