osx_image: xcode9
language: objective-c

env:
  matrix:
    - DEVICE="iPhone X (11.0)"
    - DEVICE="iPhone 7 (10.0)"
    - DEVICE="iPhone 6 (9.0)"
    - DEVICE="iPhone 5 (8.1)"

script:
  - bundle exec fastlane test

jobs:
  include:
  - stage: dependency managers
    script: bundle exec fastlane pod_lint
  -
    script: bundle exec fastlane carthage_lint

deploy:
  - provider: script
    script: bundle exec fastlane release
    skip_cleanup: true
    on:
      repo: fjcaetano/ReCaptcha
      tags: true
